project:
  type: website
  output-dir: docs

website:
  title: "Iz Leitch"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - href: Iz Leitch Resume.pdf
        text: CV

format:
  html:
    theme: solar
    css: styles.css
    toc: true



